---
os: linux
dist: focal

language: minimal

jobs:
  include:
    - name: Unit Tests
      language: python
      services:
        - postgresql
      install:
        - pip install -r requirements.txt
      env:
        -ENS_TEST_MODE=true
        -ENS_EMAIL_DISABLE=true
        -PYTHONPATH=$PYTHONPATH:$(pwd)/__app__
      git:
        submodules: false
      before_install:
        - git submodule update --init --recursive
      before_script:
        - psql -c "CREATE DATABASE testdb;" -U postgres
      script:
        - pytest -vv
    
    # - name: Lint Python
    #   language: python
    #   python: 3.9
    #   before_script: pip install flake8
    #   script: flake8 . --statistics --count