

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      language: python
      services:
        - postgresql
      install:
        - pip install -r requirements.txt
      env:
        -CROP_SQL_HOST="localhost"
        -CROP_SQL_USER="postgres"
        -CROP_SQL_PASS="postgres"
        -CROP_SQL_DBNAME="testdb"
        -CROP_SQL_PORT="5432"
        -PYTHONPATH=$PYTHONPATH:$(pwd)
      git:
        submodules: false
      before_install:
        - git submodule update --init --recursive
      before_script:
        - psql -c "CREATE DATABASE testdb;" -U postgres
      script:
        - pytest -vv